don't convert to unicode when emitting redis protocol
this fixes the following error seen while emitting redis protocol from
an rdb file

    $ rdb -c protocol dump.rdb
    *2
    $6
    SELECT
    $1
    0
    *3
    $3
    SET
    $98
    123456/Deetz/abc-123/1:2/2015-07-09T14:00:00.000Z
    Traceback (most recent call last):
      File "/usr/local/bin/rdb", line 9, in <module>
        load_entry_point('rdbtools==0.1.6', 'console_scripts', 'rdb')()
      File "/usr/local/lib/python2.7/dist-packages/rdbtools/cli/rdb.py", line 82, in main
        parser.parse(dump_file)
      File "/usr/local/lib/python2.7/dist-packages/rdbtools/parser.py", line 306, in parse
        self.read_object(f, data_type)
      File "/usr/local/lib/python2.7/dist-packages/rdbtools/parser.py", line 359, in read_object
        self._callback.set(self._key, val, self._expiry, info={'encoding':'string'})
      File "/usr/local/lib/python2.7/dist-packages/rdbtools/callbacks.py", line 309, in set
        self.emit('SET', key, value)
      File "/usr/local/lib/python2.7/dist-packages/rdbtools/callbacks.py", line 298, in emit
        self._out.write(u"$" + unicode(len(unicode(arg))) + u"\r\n")
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xd8 in position 0: ordinal not in range(128)